### ISSUE TITLE
error: legacy-install-failure

### ISSUE THREAD

**Issue by D1ffic00lt** [ColdHeat/pybluemonday#35]
```
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
Collecting pybluemonday
  Using cached pybluemonday-0.0.9.tar.gz (8.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cffi~=1.1 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from pybluemonday) (1.15.1)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from cffi~=1.1->pybluemonday) (2.20)
Building wheels for collected packages: pybluemonday
  Building wheel for pybluemonday (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      uname_result(system='Windows', node='brix', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
      make: *** No rule to make target 'clean'.  Stop.
      make: *** No rule to make target 'so'.  Stop.
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      Requirement already satisfied: cffi~=1.1 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (1.15.1)
      Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from cffi~=1.1) (2.20)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      make: *** No rule to make target 'ffi'.  Stop.
      C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-38
      creating build\lib.win32-cpython-38\pybluemonday
      copying pybluemonday\__init__.py -> build\lib.win32-cpython-38\pybluemonday
      creating build\lib.win32-cpython-38\tests
      copying tests\test_memory_leaks.py -> build\lib.win32-cpython-38\tests
      copying tests\__init__.py -> build\lib.win32-cpython-38\tests
      creating build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\test_policies.py -> build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\test_sanitize.py -> build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\__init__.py -> build\lib.win32-cpython-38\tests\bluemonday
      creating build\lib.win32-cpython-38\tests\html_sanitizer
      copying tests\html_sanitizer\test_sanitize.py -> build\lib.win32-cpython-38\tests\html_sanitizer
      copying tests\html_sanitizer\__init__.py -> build\lib.win32-cpython-38\tests\html_sanitizer
      running build_ext
      $ GOPATH='C:\Users\user\AppData\Local\Temp\tmpxsp8wog7' go get -d
      $ CGO_CFLAGS='-IC:\Users\user\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\user\AppData\Local\Programs\Python\Python38-32\Include' CGO_LDFLAGS='-LC:\Users\user\AppData\Local\Programs\Python\Python38-32\libs -lpython38' GOPATH='C:\Users\user\AppData\Local\Temp\tmpxsp8wog7' go build -buildmode=c-shared -o 'C:\Users\user\AppData\Local\Temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\build\lib.win32-cpython-38\pybluemonday\bluemonday.cp38-win32.pyd'
      # runtime/cgo
      cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\setup.py", line 49, in <module>
          setuptools.setup(
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "c:\users\user\appdata\local\temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\.eggs\setuptools_golang-2.3.0-py3.8.egg\setuptools_golang.py", line 166, in build_extension
          _check_call(cmd_build, cwd=pkg_path, env=env)
        File "c:\users\user\appdata\local\temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\.eggs\setuptools_golang-2.3.0-py3.8.egg\setuptools_golang.py", line 111, in _check_call
          subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('go', 'build', '-buildmode=c-shared', '-o', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-08xdknnw\\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\\build\\lib.win32-cpython-38\\pybluemonday\\bluemonday.cp38-win32.pyd')' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybluemonday
  Running setup.py clean for pybluemonday
Failed to build pybluemonday
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
Installing collected packages: pybluemonday
  Running setup.py install for pybluemonday ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pybluemonday did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      uname_result(system='Windows', node='brix', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
      make: *** No rule to make target 'clean'.  Stop.
      make: *** No rule to make target 'so'.  Stop.
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      Requirement already satisfied: cffi~=1.1 in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (1.15.1)
      Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages (from cffi~=1.1) (2.20)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
      make: *** No rule to make target 'ffi'.  Stop.
      C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-38
      creating build\lib.win32-cpython-38\pybluemonday
      copying pybluemonday\__init__.py -> build\lib.win32-cpython-38\pybluemonday
      creating build\lib.win32-cpython-38\tests
      copying tests\test_memory_leaks.py -> build\lib.win32-cpython-38\tests
      copying tests\__init__.py -> build\lib.win32-cpython-38\tests
      creating build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\test_policies.py -> build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\test_sanitize.py -> build\lib.win32-cpython-38\tests\bluemonday
      copying tests\bluemonday\__init__.py -> build\lib.win32-cpython-38\tests\bluemonday
      creating build\lib.win32-cpython-38\tests\html_sanitizer
      copying tests\html_sanitizer\test_sanitize.py -> build\lib.win32-cpython-38\tests\html_sanitizer
      copying tests\html_sanitizer\__init__.py -> build\lib.win32-cpython-38\tests\html_sanitizer
      running build_ext
      $ GOPATH='C:\Users\user\AppData\Local\Temp\tmp48a9ww70' go get -d
      $ CGO_CFLAGS='-IC:\Users\user\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\user\AppData\Local\Programs\Python\Python38-32\Include' CGO_LDFLAGS='-LC:\Users\user\AppData\Local\Programs\Python\Python38-32\libs -lpython38' GOPATH='C:\Users\user\AppData\Local\Temp\tmp48a9ww70' go build -buildmode=c-shared -o 'C:\Users\user\AppData\Local\Temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\build\lib.win32-cpython-38\pybluemonday\bluemonday.cp38-win32.pyd'
      # runtime/cgo
      cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\setup.py", line 49, in <module>
          setuptools.setup(
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
          self.build_extension(ext)
        File "c:\users\user\appdata\local\temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\.eggs\setuptools_golang-2.3.0-py3.8.egg\setuptools_golang.py", line 166, in build_extension
          _check_call(cmd_build, cwd=pkg_path, env=env)
        File "c:\users\user\appdata\local\temp\pip-install-08xdknnw\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\.eggs\setuptools_golang-2.3.0-py3.8.egg\setuptools_golang.py", line 111, in _check_call
          subprocess.check_call(cmd, cwd=cwd, env=dict(os.environ, **env))
        File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('go', 'build', '-buildmode=c-shared', '-o', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-08xdknnw\\pybluemonday_05c8b3035fc2444aae9eef8a37462acc\\build\\lib.win32-cpython-38\\pybluemonday\\bluemonday.cp38-win32.pyd')' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pybluemonday

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
WARNING: Ignoring invalid distribution -ffi (c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages)
```

**Comment by Jagorrim** [comment]
I fixed it when i turned python version from 3.12 to 3.10. But now i'm trying to fix another problem
